import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Favorites",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-14 bg-gradient-to-r from-cyan-500 to-blue-500">
        {children}
      </body>
    </html>
  );
}
