import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-gradient-to-l from-cyan-500 to-blue-500 bg-no-repeat bg-fixed">
        {children}
      </body>
    </html>
  );
}
